# Generated by Django 5.1.6 on 2025-02-21 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='repostory',
            new_name='repository',
        ),
    ]
